---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: users-service-rs
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata: 
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: shaikkhajaibrahim/libuserssvc:1.0
          resources:
            requests:
              cpu: 0.2
              memory: 250Mi
            limits:
              cpu: 0.3
              memory: 500Mi          
          env:
            - name: DATABASE_URL
              value: postgresql://user:password@users-db:5432/usersdb
            - name: SECRET_KEY
              value: YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:  
  selector:
    app: users        
  ports:
    - port: 8000
      targetPort: 8000
