apiVersion: v1
kind: ConfigMap
metadata:
  name: books-service-config
data:
  DATABASE_URL: postgresql://user:password@books-db:5432/booksdb
  SECRET_KEY: YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k