apiVersion: v1
kind: ConfigMap
metadata:
  name: users-service-config
data: 
  DATABASE_URL: postgresql://user:password@users-db:5432/usersdb
  SECRET_KEY: YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k
