---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-service
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: books-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: books-service
    spec:
      containers:
        - name: books-service
          image: shaikkhajaibrahim/libbookssvc:1.0
          env:
            - name: DATABASE_URL
              value: postgresql://user:password@books-db:5432/booksdb
            - name: SECRET_KEY
              value: YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k
          resources:
            requests:
              cpu: 0.1
              memory: 150Mi
            limits:
              cpu: 0.25
              memory: 250Mi
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: books-service