---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  annotations:
  
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata: 
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: shaikkhajaibrahim/libwebstore:1.0
          env:
            - name: REACT_APP_BACKEND_API_URL
              value: http://users-svc:8000/api/v1
            - name: REACT_APP_BOOKS_API_URL
              value: http://books-svc:8000/api/v1/books
            - name: REACT_APP_USERS_API_URL
              value: http://users-svc:8000/api/v1/users
          resources:
            requests:
              cpu: 0.1
              memory: 300Mi
            limits:
              cpu: 0.25
              memory: 500Mi
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32767